enum ROUTES {
  //LoginFlow
  Login = 'Login',
  ForgottenPass = 'ForgottenPass',
  OneTimePassword = 'OneTimePassword',
  Notifications = 'Notifications',
  EmailSend = 'EmailSend',
  ResetPassword = 'ResetPassword',
  SuccessPassword = 'SuccessPassword',
  EnterPin = 'EnterPin',
  //DashboardFlow
  Home = 'Home',
  Account = 'Account',
  EditField = 'EditField',
  Settings = 'Settings',
  PersonalInfo = 'PersonalInfo',
  Password = 'Password',
  ContactUs = 'Contact us',
  AccountDetails = 'AccountDetails',
  AccountStatement = 'AccountStatement',
  FeeStatement = 'FeeStatement',
  ClientStatement = 'ClientStatement',
  ClientSummaryStatement = 'ClientSummaryStatement',
  MessageSent = 'MessageSent',
  NotificationsList = 'NotificationsList',
  SearchTransaction = 'SearchTransaction',
  DocumentPreview = 'DocumentPreview',
  //MoneyTransferFlow
  ToOwnAccount = 'ToOwnAccount',
  EnterAmount = 'EnterAmount',
  ConfirmTransfer = 'ConfirmTransfer',
  ToAnotherBank = 'ToAnotherBank',
  CreatePayment = 'CreatePayment',
  SuccessTransaction = 'SuccessTransaction',
  AddTransactionToFavorites = 'AddTransactionToFavorites',
  TransactionAddedToFavorites = 'TransactionAddedToFavorites',
  ToMoneyGateFirstStep = 'ToMoneyGateFirstStep',
  ToMoneyGateSecondStep = 'ToMoneyGateSecondStep',
  FavouritesTransactions = 'FavouritesTransactions',
  TransactionDetails = 'TransactionDetails',
  Filter = ' Filter',
  Exchange = 'Exchange',
  CurrencyRates = 'CurrencyRates',
  RatesHistory = 'RatesHistory',
  BulkFileUpload = 'BulkFileUpload',
  BulkFilePayment = 'BulkFilePayment',
}

export default ROUTES
