import colors from './colors'

export default {
  white: colors.white,
  white10: colors.white10,
  white12: colors.white12,
  white20: colors.white20,
  purple: colors.purple,
  purple85: colors.purple85,
  purple55: colors.purple55,
  purple25: colors.purple25,
  pumpkin: colors.pumpkin,
  pumpkin21: colors.pumpkin21,
  pumpkin85: colors.pumpkin85,
  pumpkin55: colors.pumpkin55,
  pumpkin25: colors.pumpkin25,
  black: colors.black,
  lightGray: colors.lightGray,
  midGray: colors.midGray,
  darkGray: colors.darkGray,
  lightMagentaPink: colors.lightMagentaPink,
  lightPowder: colors.lightPowder,
  green: colors.green,
  gray85: colors.gray85,
  lightPurple: colors.lightPurple,
  purple5: colors.purple5,
  mintCream: colors.mintCream,
  gray95: colors.gray95,
  lightBeige: colors.lightBeige,
  lightYellow: colors.lightYellow,
  gray: colors.gray,
  transparent: colors.transparent,
  darkTransparent: colors.darkTransparent,
  lightTransparent: colors.lightTransparent,
  red: colors.red,
  darkRed: colors.darkRed,
  yellow: colors.yellow,
  paleGreen: colors.paleGreen,
  scarlet: colors.scarlet,
}
